### ISSUE TITLE
Doesn't work with react code

### ISSUE THREAD

**Issue by imcvampire** [kalimahapps/eslint-plugin-tailwind#8]
Thank you for a very useful package! 

After some tests, seems like this plugin only works with Vue but not React.

**Comment by sitch** [comment]
Bummer was really hoping this would work on react

**Comment by abdul-alhasany** [comment]
The plugin was designed for vue because I mostly work with it. @imcvampire @sitch if you have any public code I can test, I might be able to make it work with react code.

**Comment by sitch** [comment]
Looks like modifying this to work with the AST should get it going: https://github.com/francoismassart/eslint-plugin-tailwindcss/blob/master/lib/rules/classnames-order.js

**Comment by sitch** [comment]
Using something like this would also improve this plugin's ability to work with literals/arrays/object expressions in vue as well

**Comment by imcvampire** [comment]
@sitch seems like you know the solution? Do you have any free time to submit a PR

**Comment by sitch** [comment]
I got it half way there, but looks like you need to rewrite the whole thing bc the logic in the TailwindMultiLine is tied to the VAttribute

**Comment by sitch** [comment]
Bah just found this `eslint-plugin-readable-tailwind`
