### ISSUE TITLE
Sort Classes Similar To prettier-plugin-tailwindcss

### ISSUE THREAD

**Issue by ShayanTheNerd** [kalimahapps/eslint-plugin-tailwind#9]
Thank you for developing this plugin. Even though there are some naming conventions I don't really like, and it's not as feature-rich as [eslint-plugin-tailwindcss](https://github.com/francoismassart/eslint-plugin-tailwindcss), this is still the only plugin I found that supports both ESLint >= v9 and TailwindCSS >= v4-alpha.

It'd be great if the plugin sorted classes the way [prettier-plugin-tailwindcss](https://github.com/tailwindlabs/prettier-plugin-tailwindcss) does, which makes life easier when migrating from a codebase formatted as such, or if you're like me and believe that order makes the code more readable. In case you don't like to change the default behavior of the plugin, having an opt-in option sounds good, too.

**Comment by abdul-alhasany** [comment]
Yes. I think it is a good idea to add more sorting options such as ASC, tailwind style .. etc. However, it is a very big task and I don't think I have the time for that at the moment. 
I developed this plugin to fit my projects needs and I think others see the benifit in it too. Hopefully in the feture I will try to implment more features including sorting style.
Also, a PR is welcome.
